name: Run example

on:
  push:
  pull_request:
  schedule:
  - cron: 0 8 * * *

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  demo:
    name: runs demo with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
        - '3.10'
        - '3.9'
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup python ${{ matrix.py }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}
    - name: Install dvc-stage
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install .
    - name: Run example
      run: |
        cd examples
        pip install .
        dvc repro
